x-shared-variables: &shared-variables
  MODEL_VERSION: "tiny"

services:
  # whisper_api:
  #   build:
  #     context: ./stt
  #     args: *shared-variables
  #   container_name: "whisper_api"
  #   environment: *shared-variables
  #   ports:
  #     - 5000:5000

  mysql:
    container_name: mysql
    image: mysql:9.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    network_mode: "host"
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TUNNEL_TOKEN=eyJhIjoiZWEwNTc1NjY2YzczNWZmZjBjMmE5MzczN2M0YzNmN2EiLCJ0IjoiNTZmN2QwMGMtYmYyZi00YjdiLThjODktYTg5OWYyYWM5Njg4IiwicyI6Ik5qVmpZakUyWkdZdFl6RmpaUzAwTVRZMUxXSTFObUl0TURFd1pUWXhaREJsT0RnNSJ9"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
